// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { z } from "npm:zod@^4.4.3";
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List portfolio projects",
  description: "Retrieve Sandeep Lamture's portfolio projects with title, description, tech stack, live demo URL, and source code URL.",
  inputSchema: {
    featured_only: z.boolean().optional().describe("If true, only return featured projects.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ featured_only }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    let query = supabase.from("projects").select("title, description, tech_stack, live_url, github_url, featured").order("featured", { ascending: false }).order("created_at", { ascending: false });
    if (featured_only) query = query.eq("featured", true);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { projects: data }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_blog_posts_default = defineTool2({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published blog posts from Sandeep Lamture's portfolio, returning title, slug, excerpt, tags, and creation date.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Maximum number of posts to return (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    const { data, error } = await supabase.from("blog_posts").select("title, slug, excerpt, tags, created_at").eq("published", true).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { posts: data }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
import { z as z3 } from "npm:zod@^4.4.3";
var get_blog_post_default = defineTool3({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Fetch the full content of a published blog post by its slug from Sandeep Lamture's portfolio.",
  inputSchema: {
    slug: z3.string().min(1).describe("URL slug of the blog post.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    const { data, error } = await supabase.from("blog_posts").select("title, slug, excerpt, content, tags, created_at, updated_at").eq("slug", slug).eq("published", true).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `No post found with slug "${slug}"` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_profile_default = defineTool4({
  name: "get_profile",
  title: "Get profile & contact info",
  description: "Get Sandeep Lamture's professional profile: role, experience summary, tech skills, and contact information.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const profile = {
      name: "Sandeep Lamture",
      title: "React Developer",
      experience_years: 4,
      location: "Pune, Maharashtra, India",
      summary: "React Developer with 4+ years of experience building scalable, high-performance web applications. Currently at Tata Consultancy Services (TCS).",
      contact: {
        email: "sandylamture03@gmail.com",
        phone: "+91 9503250303",
        linkedin: "https://www.linkedin.com/in/sandeep-lamture-00ba4779/",
        github: "https://github.com/Sandylamture03",
        portfolio: "https://portfolio.lamsan.online"
      },
      skills: {
        frontend: [
          "React.js",
          "TypeScript",
          "JavaScript",
          "Redux",
          "TailwindCSS",
          "HTML5",
          "CSS3",
          "SCSS"
        ],
        tools: ["Git", "GitHub", "VS Code", "Webpack", "Vite"],
        apis: ["REST APIs", "GraphQL", "Axios", "React Query", "WebSockets"],
        cloud: ["AWS (Basic)", "Firebase", "Vercel", "Netlify"]
      },
      experience: [
        {
          company: "Tata Consultancy Services (TCS)",
          role: "React Developer",
          period: "Oct 2022 - Present"
        },
        {
          company: "Randstad",
          role: "Frontend Developer",
          period: "Sep 2021 - Sep 2022"
        }
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/tools/submit-contact.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.89.0";
import { z as z4 } from "npm:zod@^4.4.3";
var submit_contact_default = defineTool5({
  name: "submit_contact_message",
  title: "Send contact message",
  description: "Send a contact message to Sandeep Lamture through his portfolio. The message is saved and Sandeep is notified by email.",
  inputSchema: {
    name: z4.string().trim().min(1).max(100).describe("Sender's full name."),
    email: z4.string().trim().email().max(255).describe("Sender's email address."),
    message: z4.string().trim().min(10).max(1e3).describe("Message body (10-1000 characters).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, email, message }) => {
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    const { error } = await supabase.from("contact_submissions").insert([{ name, email, message }]);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    try {
      await supabase.functions.invoke("send-contact-email", {
        body: { name, email, message }
      });
    } catch (e) {
    }
    return {
      content: [{ type: "text", text: "Message sent successfully. Sandeep will get back to you soon." }],
      structuredContent: { success: true }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "sandeep-portfolio-mcp",
  title: "Sandeep Lamture Portfolio",
  version: "0.1.0",
  instructions: "Tools for exploring Sandeep Lamture's portfolio: list projects, browse blog posts, view profile & skills, and send contact messages.",
  tools: [get_profile_default, list_projects_default, list_blog_posts_default, get_blog_post_default, submit_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
